wandb_version: 1

accelerator:
  value: GPU
batch_size:
  value: 128
epochs:
  value: 10
learning_rate:
  value: 0.0001
max_length:
  value: 64
model_name:
  value: bert-base-multilingual-cased
train_splits:
  value: 2
translation:
  value: false
