'entity': 'shesh6'
'project': 'contradictory-dear-watson'
'method': 'bayes'
'metric':
  'name': 'val_loss'
  'goal': 'minimize'   
'parameters': {
    'model_name':
        'values': ["bert-base-multilingual-cased"]
    'translation':
        'values': [False]
    'max_length':
        'values': [32,64]
    'batch_size':
        'values': [64,128]
    'train_splits':
        'values': [2]
    'epochs':
        'values': [5, 10]
    'learning_rate':
        'values': [1e-2, 1e-4]
    "accelerator":
        'values': ["GPU"]
